### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by jampow** [jiangmiao/node-curl#1]
Hi... I'm trying the basic example with google.com and it's givingme the error:

Error: Cannot find module '/media/arquivos/projetos/javaScript/jornaleiro/node_modules/node-curl/lib/../build/default/node-curl'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/media/arquivos/projetos/javaScript/jornaleiro/node_modules/node-curl/lib/curl.js:10:12)
    at Object.<anonymous> (/media/arquivos/projetos/javaScript/jornaleiro/node_modules/node-curl/lib/curl.js:155:4)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)

I try to find out the solution, but I'm a node noob yet... I didn't find the module.js or the default folder inside build..

I'm using node.js 0.6.18, and before I was using 0.6.0 with this same error.

Tks

**Comment by jiangmiao** [comment]
What's the installation output?
Mine is
Node Version

```
[miao@myhost ~]$ node -v
v0.6.18
```

Install node-curl

```
[miao@myhost ~]$ npm install node-curl
npm WARN /etc/npmrc Cannot set prefix in globalconfig file
npm http GET http://registry.npmjs.com/node-curl
npm http 200 http://registry.npmjs.com/node-curl

> node-curl@0.1.2 install /home/miao/node_modules/node-curl
> sh src/generate_curl_options_list.sh && node-waf configure build || true

generate src/integer_options.h
generate src/string_options.h
generate src/integer_infos.h
generate src/string_infos.h
generate src/double_infos.h
Setting srcdir to                        : /home/miao/node_modules/node-curl 
Setting blddir to                        : /home/miao/node_modules/node-curl/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr 
'configure' finished successfully (0.209s)
Waf: Entering directory `/home/miao/node_modules/node-curl/build'
[1/2] cxx: src/node-curl.cc -> build/Release/src/node-curl_1.o
[2/2] cxx_link: build/Release/src/node-curl_1.o -> build/Release/node-curl.node
Waf: Leaving directory `/home/miao/node_modules/node-curl/build'
'build' finished successfully (3.895s)
node-curl@0.1.2 ./node_modules/node-curl
```

The Files in node-curl/build

```
[miao@myhost ~]$ find node_modules/node-curl/build/
node_modules/node-curl/build/
node_modules/node-curl/build/.wafpickle-7
node_modules/node-curl/build/config.log
node_modules/node-curl/build/c4che
node_modules/node-curl/build/c4che/build.config.py
node_modules/node-curl/build/c4che/Release.cache.py
node_modules/node-curl/build/Release
node_modules/node-curl/build/Release/node-curl.node
node_modules/node-curl/build/Release/src
node_modules/node-curl/build/Release/src/node-curl_1.o
```

Run one of the example curl.js

```
[miao@myhost ~]$ node node_modules/node-curl/examples/curl.js google.com
* About to connect() to google.com port 80 (#0)
*   Trying 203.208.46.180...
* Connected to google.com (203.208.46.180) port 80 (#0)
* Connected to google.com (203.208.46.180) port 80 (#0)
> GET / HTTP/1.1
Host: google.com
Accept: */*
Accept-Encoding: gzip
...
...
```

**Comment by jampow** [comment]
The problem is on build I got this:

```
Build failed:  -> task failed (err #1): 
{task: cxx node-curl.cc -> node-curl_1.o}
```

update my npm but I still getting this message on install I find out some options on Google, but nothing worked.. any sugestion?

tks for help!

**Comment by jiangmiao** [comment]
Have you installed libcurl-dev? the file node-curl read to generate header is /usr/include/curl/curl.h
What's the full error message?

**Comment by jampow** [comment]
Oh! great.. it was libcurl-dev, now it's builded, but, in my code and examples I'm getting another error

```
/media/arquivos/projetos/javaScript/jornaleiro/node_modules/node-curl/lib/curl.js:29
      throw new Error("unsupported option " + option);
            ^
Error: unsupported option ACCEPT_ENCODING
    at [object Object].setopt (/media/arquivos/projetos/javaScript/jornaleiro/node_modules/node-curl/lib/curl.js:29:13)
    at /media/arquivos/projetos/javaScript/jornaleiro/node_modules/node-curl/lib/curl.js:88:7
    at Object.<anonymous> (/media/arquivos/projetos/javaScript/jornaleiro/teste.js:3:1)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)
    at EventEmitter._tickCallback (node.js:190:38)
```

I tried with this libs:
- libcurl4-openssl-dev 7.21.3-1ubuntu1.5
- libcurl4-nss-dev 7.21.3-1ubuntu1.5
- libcurl4-gnutls-dev 7.21.3-1ubuntu1.5

I removed and re-installed node-curl before test and all gave me this same message.

Do you think that can be my libcurl-dev or something with node-curl?

one more time... tks for the help!

**Comment by jiangmiao** [comment]
For this error message, maybe your curl version is before 7.21.6

http://curl.haxx.se/libcurl/c/curl_easy_setopt.html

CURLOPT_ACCEPT_ENCODING

Sets the contents of the Accept-Encoding: header sent in a HTTP request, and enables decoding of a response when a Content-Encoding: header is received. Three encodings are supported: identity, which does nothing, deflate which requests the server to compress its response using the zlib algorithm, and gzip which requests the gzip algorithm. If a zero-length string is set, then an Accept-Encoding: header containing all supported encodings is sent.

This is a request, not an order; the server may or may not do it. This option must be set (to any non-NULL value) or else any unsolicited encoding done by the server is ignored. See the special file lib/README.encoding for details.

(This option was called CURLOPT_ENCODING before 7.21.6)

**Comment by jiangmiao** [comment]
Yes, I see your libcurl version is 7.21.3

libcurl4-openssl-dev should be enough.

**Comment by jampow** [comment]
Yes... it's alive!! 

I renamed this parameter to the old version and worked..

I'll show you the project when I finish, thank you very much for your help!!

**Comment by jiangmiao** [comment]
You're welcome, Glad to it works :)
