### ISSUE TITLE
CookieList returning same data for each cookie

### ISSUE THREAD

**Issue by stephen-corgiat** [jiangmiao/node-curl#2]
Running examples/test.js on my system returns the correct number of cookies, but the cookie data is the same for each one. 

To summarize test.js's output:

Open: www.google.com:
- Added cookie PREF="ID=6ef7f0cf705f5289:FF=0:TM=1338154592:LM=1338154592:S=9OrGO0C7DRgMcigW" for domain google.com, path /, expire 1401226592
- Added cookie NID="60=RBWHQ3I1T6h5eyH6Grb-a0i1z2lucuCgHpaEISYrD_32240arr2n5lrkQFskCOh0nzX1k2bYkMuH5QocCrMp_sXdIddA-4a5pKjMTVYnOnttk-J2mLATTrPpHW3PO4L9" for domain google.com, path /, expire 1353965792

Cookielist:
[ '.google.com\tTRUE\t/\tFALSE\t1401226592\tPREF\tID=6ef7f0cf705f5289:FF=0:TM=1338154592:LM=1338154592:S=9OrGO0C7DRgMcigW',
 '.google.com\tTRUE\t/\tFALSE\t1401226592\tPREF\tID=6ef7f0cf705f5289:FF=0:TM=1338154592:LM=1338154592:S=9OrGO0C7DRgMcigW' ]

When loading Yahoo.com, cookielist contains:
[ '.yahoo.com\tTRUE\t/\tFALSE\t1306618591\tIU\tdeleted',
  '.yahoo.com\tTRUE\t/\tFALSE\t1306618591\tIU\tdeleted',
  '.yahoo.com\tTRUE\t/\tFALSE\t1306618591\tIU\tdeleted',
  '.yahoo.com\tTRUE\t/\tFALSE\t1306618591\tIU\tdeleted',
  '.yahoo.com\tTRUE\t/\tFALSE\t1306618591\tIU\tdeleted',
  '.yahoo.com\tTRUE\t/\tFALSE\t1306618591\tIU\tdeleted',
  '.yahoo.com\tTRUE\t/\tFALSE\t1306618591\tIU\tdeleted',
  '.yahoo.com\tTRUE\t/\tFALSE\t1306618591\tIU\tdeleted',
  '.yahoo.com\tTRUE\t/\tFALSE\t1306618591\tIU\tdeleted' ]

I'm using curl v7.26.0,  node v0.6.17.

Thanks for making this awesome module!

**Comment by jiangmiao** [comment]
Thanks for reporting,
I changed the module a lot, the new way to use node-curl

```
curl = require('node-curl');
curl('www.google.com', function(err) {
  console.info(this.status);
  console.info('-----');
  console.info(this.body);
  console.info('-----');
  console.info(this.info('SIZE_DOWNLOAD'));
});
```

the (err, res) in callback still works, the res actually equals curl,  maybe removed res in future.
