### ISSUE TITLE
install problem...

### ISSUE THREAD

**Issue by murvinlai** [jiangmiao/node-curl#4]
I got this when trying to install:

npm http GET https://registry.npmjs.org/node-curl
npm http 200 https://registry.npmjs.org/node-curl
npm http GET https://registry.npmjs.org/node-curl/-/node-curl-0.1.4.tgz
npm http 200 https://registry.npmjs.org/node-curl/-/node-curl-0.1.4.tgz

> node-curl@0.1.4 install /opt/apps/nodeServer/service-layer-server/node_modules/node-curl
> sh src/generate_curl_options_list.sh && node-waf configure build || true

generate src/integer_options.h
cat: /usr/include/curl/curl.h: No such file or directory
generate src/string_options.h
cat: /usr/include/curl/curl.h: No such file or directory
generate src/integer_infos.h
cat: /usr/include/curl/curl.h: No such file or directory
generate src/string_infos.h
cat: /usr/include/curl/curl.h: No such file or directory
generate src/double_infos.h
cat: /usr/include/curl/curl.h: No such file or directory
sh: node-waf: not found

and when run, i got this:
$ node testCurl.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/opt/apps/nodeServer/service-layer-server/node_modules/node-curl/lib/../build/default/node-curl'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/opt/apps/nodeServer/service-layer-server/node_modules/node-curl/lib/curl.js:8:12)
    at Object.<anonymous> (/opt/apps/nodeServer/service-layer-server/node_modules/node-curl/lib/curl.js:79:4)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

I'm using Node.js 0.8.4  is hat a version problem?

**Comment by jiangmiao** [comment]
need libcurl-dev installed. similar issue #1

**Comment by murvinlai** [comment]
Got complain for node-wap.

node-wap is not supported in node.js 0.8+ anymore.. what should I do?

**Comment by jiangmiao** [comment]
what is node-wap? Do you mean node-waf?
I just tested in node v0.8.5 and install succeeded.

**Comment by murvinlai** [comment]
I got this:

npm http GET https://registry.npmjs.org/node-waf
npm http 404 https://registry.npmjs.org/node-waf
npm ERR! 404 'node-waf' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Maybe try 'npm search waf'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

**Comment by murvinlai** [comment]
and that's the one for install node-curl

> node-curl@0.1.4 install
> /opt/apps/nodeServer/service-layer-server/node_modules/node-curl
> sh src/generate_curl_options_list.sh && node-waf configure build || true

generate src/integer_options.h
generate src/string_options.h
generate src/integer_infos.h
generate src/string_infos.h
generate src/double_infos.h
sh: node-waf: not found

**Comment by jiangmiao** [comment]
Try to install nodejs-dev http://stackoverflow.com/questions/8662532/missing-node-waf-when-installing-nowjs

and do you see any node-gyp related things when compile other native module?

**Comment by murvinlai** [comment]
Well. it is not found either.

$npm install nodejs-dev
npm http GET https://registry.npmjs.org/nodejs-dev
npm http 404 https://registry.npmjs.org/nodejs-dev
npm ERR! 404 'nodejs-dev' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

**Comment by jiangmiao** [comment]
if you are using Debian/Ubuntu try `apt-get install nodejs-dev`
