### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by srathbun** [jiangmiao/node-curl#5]
The docs indicate that to get the body for a message, you should use `this.body`. However, that does not work.

There is an undocumented input to the callback function `res`. The res object contains body. Which direction is the library moving in?

**Comment by jiangmiao** [comment]
res is old version compatible, it exactly equals curl, and the callback is called by `callback.call(curl)`, so this, curl, and res should be same thing.

**Comment by srathbun** [comment]
Thanks, I'll adjust it when I have time.
