### ISSUE TITLE
npm install node-curl fails -- Build failed:  -> task failed (err #1):  	{task: cxx node-curl.cc -> node-curl_1.o}

### ISSUE THREAD

**Issue by carmstrong** [jiangmiao/node-curl#8]
I'm leveraging node-curl in my latest project, and when I try to deploy to Heroku I'm getting the following errors:

2012-11-23T17:48:15+00:00 app[web.1]: [Fri Nov 23 2012 17:48:15 GMT+0000 (UTC)] ERROR Unable to load /app/scripts/deploy: Error: Cannot find module '/app/node_modules/node-curl/lib/../build/default/node-curl'
2012-11-23T17:48:15+00:00 app[web.1]: Error: Cannot find module '/app/node_modules/node-curl/lib/../build/default/node-curl'
2012-11-23T17:48:15+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/node-curl/lib/curl.js:79:4)
2012-11-23T17:48:15+00:00 app[web.1]:     at Module.require (module.js:359:17)
2012-11-23T17:48:15+00:00 app[web.1]:     at Function._resolveFilename (module.js:337:11)
2012-11-23T17:48:15+00:00 app[web.1]:     at require (module.js:375:17)
2012-11-23T17:48:15+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/node-curl/lib/curl.js:8:12)
2012-11-23T17:48:15+00:00 app[web.1]:     at Module.load (module.js:353:31)
2012-11-23T17:48:15+00:00 app[web.1]:     at Function._load (module.js:311:12)

As part of my debugging I ran npm install node-curl locally, and got the following:

carmstrong:resubot chris$ npm install node-curl
npm http GET https://registry.npmjs.org/node-curl
npm http 200 https://registry.npmjs.org/node-curl
npm http GET https://registry.npmjs.org/node-curl/-/node-curl-0.1.4.tgz
npm http 200 https://registry.npmjs.org/node-curl/-/node-curl-0.1.4.tgz

> node-curl@0.1.4 install /Users/chris/code/JulySixteen/resubot/node_modules/node-curl
> sh src/generate_curl_options_list.sh && node-waf configure build || true

generate src/integer_options.h
date: illegal option -- R
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
generate src/string_options.h
date: illegal option -- R
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
generate src/integer_infos.h
date: illegal option -- R
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
generate src/string_infos.h
date: illegal option -- R
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
generate src/double_infos.h
date: illegal option -- R
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
Setting srcdir to                        : /Users/chris/code/JulySixteen/resubot/node_modules/node-curl 
Setting blddir to                        : /Users/chris/code/JulySixteen/resubot/node_modules/node-curl/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.594s)
Waf: Entering directory `/Users/chris/code/JulySixteen/resubot/node_modules/node-curl/build'
[1/2] cxx: src/node-curl.cc -> build/Release/src/node-curl_1.o
In file included from ../src/node-curl.cc:1:
../src/node-curl.h: In static member function ‘static v8::Handle<v8::Value> NodeCurl::Initialize(v8::Handle<v8::Object>)’:
../src/node-curl.h:403: error: ‘CURLOPT_MAIL_RCPT’ was not declared in this scope
../src/node-curl.h:407: error: ‘CURLOPT_RESOLVE’ was not declared in this scope
Waf: Leaving directory`/Users/chris/code/JulySixteen/resubot/node_modules/node-curl/build'
Build failed:  -> task failed (err #1): 
    {task: cxx node-curl.cc -> node-curl_1.o}
node-curl@0.1.4 node_modules/node-curl

**Comment by jiangmiao** [comment]
It might be the Linux version is difference. now I remove the date argument.
but I'm not sure it could work on Heroku or not. because if Heroku doesn't have file /usr/include/curl/curl.h or  doesn't have permission to it, the installation will still failed.

**Comment by rccc** [comment]
Got this same error installing node-curl on Ubuntu 10.04 with npm 1.0.106 and  node v0.6.6

> node-curl@0.1.6 install /var/www/nodejs/node_modules/node-curl
> sh src/generate_curl_options_list.sh && node-waf configure build || true

generate src/integer_options.h
cat: /usr/include/curl/curl.h: Aucun fichier ou dossier de ce type
generate src/string_options.h
cat: /usr/include/curl/curl.h: Aucun fichier ou dossier de ce type
generate src/integer_infos.h
cat: /usr/include/curl/curl.h: Aucun fichier ou dossier de ce type
generate src/string_infos.h
cat: /usr/include/curl/curl.h: Aucun fichier ou dossier de ce type
generate src/double_infos.h
cat: /usr/include/curl/curl.h: Aucun fichier ou dossier de ce type
Setting srcdir to                        : /var/www/nodejs/node_modules/node-curl 
Setting blddir to                        : /var/www/nodejs/node_modules/node-curl/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.028s)
Waf: Entering directory `/var/www/nodejs/node_modules/node-curl/build'
[1/2] cxx: src/node-curl.cc -> build/Release/src/node-curl_1.o
In file included from ../src/node-curl.cc:1:
../src/node-curl.h:7:23: error: curl/curl.h: Aucun fichier ou dossier de ce type
In file included from ../src/node-curl.cc:1:
../src/node-curl.h:22: error: ISO C++ forbids declaration of ‘CURLM’ with no type
../src/node-curl.h:22: error: expected ‘;’ before ‘*’ token
../src/node-curl.h:25: error: ‘CURL’ was not declared in this scope
../src/node-curl.h:25: error: template argument 1 is invalid
../src/node-curl.h:25: error: template argument 3 is invalid
../src/node-curl.h:25: error: template argument 4 is invalid
../src/node-curl.h:28: error: ISO C++ forbids declaration of ‘CURL’ with no type
../src/node-curl.h:28: error: expected ‘;’ before ‘*’ token
../src/node-curl.h:31: error: ‘curl_slist’ was not declared in this scope
../src/node-curl.h:31: error: template argument 1 is invalid
../src/node-curl.h:31: error: template argument 2 is invalid
../src/node-curl.h:124: error: ‘CURLMsg’ has not been declared
../src/node-curl.h:135: error: ‘CURLMsg’ has not been declared
../src/node-curl.h:238: error: ISO C++ forbids declaration of ‘curl_slist’ with no type
../src/node-curl.h:238: error: expected ‘;’ before ‘*’ token
../src/node-curl.cc:7: error: expected ‘;’ at end of input
../src/node-curl.cc:7: error: expected ‘}’ at end of input
In file included from ../src/node-curl.cc:1:
../src/node-curl.h: In constructor ‘NodeCurl::NodeCurl(v8::Handle<v8::Object>)’:
../src/node-curl.h:43: error: ‘curl’ was not declared in this scope
../src/node-curl.h:43: error: ‘curl_easy_init’ was not declared in this scope
../src/node-curl.h:46: error: invalid conversion from ‘const char*’ to ‘int’
../src/node-curl.h:46: error:   initializing argument 1 of ‘int raise(int)’
../src/node-curl.h:49: error: ‘CURLOPT_WRITEFUNCTION’ was not declared in this scope
../src/node-curl.h:49: error: ‘curl_easy_setopt’ was not declared in this scope
../src/node-curl.h:50: error: ‘CURLOPT_WRITEDATA’ was not declared in this scope
../src/node-curl.h: In destructor ‘NodeCurl::~NodeCurl()’:
../src/node-curl.h:58: error: ‘curl’ was not declared in this scope
../src/node-curl.h:61: error: ‘curlm’ was not declared in this scope
../src/node-curl.h:61: error: ‘curl_multi_remove_handle’ was not declared in this scope
../src/node-curl.h:62: error: ‘curl_easy_cleanup’ was not declared in this scope
../src/node-curl.h:63: error: request for member ‘erase’ in ‘NodeCurl::curls’, which is of non-class type ‘int’
../src/node-curl.h:66: error: ‘curl_slist’ was not declared in this scope
../src/node-curl.h:66: error: template argument 1 is invalid
../src/node-curl.h:66: error: template argument 2 is invalid
../src/node-curl.h:66: error: expected initializer before ‘i’
../src/node-curl.h:66: error: ‘i’ was not declared in this scope
../src/node-curl.h:66: error: ‘e’ was not declared in this scope
../src/node-curl.h:68: error: ‘slist’ was not declared in this scope
../src/node-curl.h:71: error: ‘curl_slist_free_all’ was not declared in this scope
../src/node-curl.h: In member function ‘void NodeCurl::on_error(int*)’:
../src/node-curl.h:141: error: request for member ‘data’ in ‘* msg’, which is of non-class type ‘int’
../src/node-curl.h:141: error: ‘curl_easy_strerror’ was not declared in this scope
../src/node-curl.h: In static member function ‘static v8::Handle<v8::Value> NodeCurl::getinfo(const v8::Arguments&)’:
../src/node-curl.h:152: error: ‘CURLINFO’ was not declared in this scope
../src/node-curl.h:152: error: expected ‘;’ before ‘info’
../src/node-curl.h:153: error: ‘CURLcode’ was not declared in this scope
../src/node-curl.h:153: error: expected ‘;’ before ‘code’
../src/node-curl.h:154: error: ‘code’ was not declared in this scope
../src/node-curl.h:154: error: ‘CURLE_OK’ was not declared in this scope
../src/node-curl.h:156: error: there are no arguments to ‘curl_easy_strerror’ that depend on a template parameter, so a declaration of ‘curl_easy_strerror’ must be available
../src/node-curl.h:156: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../src/node-curl.h: In static member function ‘static v8::Handle<v8::Value> NodeCurl::getinfo_slist(const v8::Arguments&)’:
../src/node-curl.h:178: error: ‘curl_slist’ was not declared in this scope
../src/node-curl.h:178: error: ‘slist’ was not declared in this scope
../src/node-curl.h:178: error: ‘cur’ was not declared in this scope
../src/node-curl.h:180: error: ‘CURLINFO’ was not declared in this scope
../src/node-curl.h:180: error: expected ‘;’ before ‘info’
../src/node-curl.h:181: error: ‘CURLcode’ was not declared in this scope
../src/node-curl.h:181: error: expected ‘;’ before ‘code’
../src/node-curl.h:182: error: ‘code’ was not declared in this scope
../src/node-curl.h:182: error: ‘CURLE_OK’ was not declared in this scope
../src/node-curl.h:184: error: ‘curl_easy_strerror’ was not declared in this scope
../src/node-curl.h:195: error: ‘curl_slist_free_all’ was not declared in this scope
../src/node-curl.h:179: warning: unused variable ‘node_curl’
../src/node-curl.h: In member function ‘v8::Handle<v8::Value> NodeCurl::setopt(v8::Handle<v8::Value>, T)’:
../src/node-curl.h:206: error: ‘curl’ was not declared in this scope
../src/node-curl.h:207: error: ‘CURLoption’ was not declared in this scope
../src/node-curl.h: In static member function ‘static v8::Handle<v8::Value> NodeCurl::setopt_slist(const v8::Arguments&)’:
../src/node-curl.h:233: error: ‘curl_slist’ was not declared in this scope
../src/node-curl.h:233: error: ‘slist’ was not declared in this scope
../src/node-curl.h:233: error: ‘value_to_slist’ was not declared in this scope
../src/node-curl.h:234: error: request for member ‘push_back’ in ‘node_curl->NodeCurl::slists’, which is of non-class type ‘int’
../src/node-curl.h: At global scope:
../src/node-curl.h:236: error: expected unqualified-id at end of input
../src/node-curl.h: In static member function ‘static v8::Handle<v8::Value> NodeCurl::getinfo(const v8::Arguments&) [with CType = int, JsClass = v8::Integer]’:
../src/node-curl.h:163:   instantiated from here
../src/node-curl.h:154: error: ‘curl_easy_strerror’ was not declared in this scope
../src/node-curl.h:163:   instantiated from here
../src/node-curl.h:151: warning: unused variable ‘node_curl’
../src/node-curl.h: In static member function ‘static v8::Handle<v8::Value> NodeCurl::getinfo(const v8::Arguments&) [with CType = char*, JsClass = v8::String]’:
../src/node-curl.h:168:   instantiated from here
../src/node-curl.h:154: error: ‘curl_easy_strerror’ was not declared in this scope
../src/node-curl.h:168:   instantiated from here
../src/node-curl.h:151: warning: unused variable ‘node_curl’
../src/node-curl.h: In static member function ‘static v8::Handle<v8::Value> NodeCurl::getinfo(const v8::Arguments&) [with CType = double, JsClass = v8::Number]’:
../src/node-curl.h:173:   instantiated from here
../src/node-curl.h:154: error: ‘curl_easy_strerror’ was not declared in this scope
../src/node-curl.h:173:   instantiated from here
../src/node-curl.h:151: warning: unused variable ‘node_curl’
../src/node-curl.h: In member function ‘v8::Handle<v8::Value> NodeCurl::setopt(v8::Handle<v8::Value>, T) [with T = int]’:
../src/node-curl.h:215:   instantiated from here
../src/node-curl.h:210: error: ‘curl_easy_setopt’ was not declared in this scope
../src/node-curl.h: In member function ‘v8::Handle<v8::Value> NodeCurl::setopt(v8::Handle<v8::Value>, T) [with T = const char*]’:
../src/node-curl.h:227:   instantiated from here
../src/node-curl.h:210: error: ‘curl_easy_setopt’ was not declared in this scope
Waf: Leaving directory`/var/www/nodejs/node_modules/node-curl/build'
Build failed:  -> task failed (err #1): 
    {task: cxx node-curl.cc -> node-curl_1.o}
node-curl@0.1.6 ./node_modules/node-curl

**Comment by jiangmiao** [comment]
The server hasn't installed libcurl. similar issue #1
